improve macos error message wrt gnu date

diff --git a/git-quick-stats b/git-quick-stats
--- a/git-quick-stats
+++ b/git-quick-stats
@@ -99,10 +99,10 @@ function checkUtils() {
     # the user that this will not work rather than having it silently bomb out
     # during runtime.
     if ! date --version >/dev/null 2>&1; then
-        echo "ERROR: You must have GNU date installed."
-        echo "If you're on macOS, please use brew to install this utility."
-        echo "Make sure the GNU version of date is symlinked to 'date', too."
-        exit 1
+	echo "ERROR: GNU date is required."
+	echo "If you're on macOS, please install it using 'brew install coreutils'."
+	echo "Ensure that your PATH is configured to use GNU date as well."
+	exit 1
     fi
 }
 
